config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tickets#index'

  namespace :api do
    post 'tickets', to: 'tickets#create'
  end

  resources :tickets, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
  validates :company_name, presence: true
  validates :crew_onsite, presence: true
  validates :address, presence: true

  belongs_to :ticket
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  validates :request_number, presence: true
  validates :sequence_number, presence: true
  validates :request_type, presence: true
  validates :request_action, presence: true
  validates :response_due_date_time, presence: true
  validates :primary_service_area_code, presence: true
  validates :additional_service_area_codes, presence: true
  validates :well_known_text, presence: true

  has_one :excavator

  accepts_nested_attributes_for :excavator
end

app/controllers/api/api_application_controller.rb
# frozen_string_literal: true

module Api
  class ApiApplicationController < ApplicationController
    UNPROCESSABLE_ENTITY_CODE = 422

    private

    def unprocessable_entity!(errors)
      error = errors.is_a?(ActiveModel::Errors) ? errors.full_messages.to_sentence : errors
      render json: { error: }, status: UNPROCESSABLE_ENTITY_CODE
    end
  end
end

app/controllers/api/tickets_controller.rb
# frozen_string_literal: true

module Api
  class TicketsController < ApiApplicationController
    skip_before_action :verify_authenticity_token

    def create
      ticket = Services::Tickets::Create.new(params.permit!).call
      return unprocessable_entity!(ticket.errors) unless ticket.valid?

      render json: { message: 'Ticket created successfully' }, status: :created
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  def index
    @tickets = Ticket.includes(:excavator).order(id: :desc).page(params[:page]).per(9)
  end

  def show
    @coordinates = ticket.well_known_text.scan(/(-?\d+\.\d+)\s(-?\d+\.\d+)/)
  end

  private

  def ticket
    @ticket ||= Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<div class="tickets">
  <h1>Tickets</h1>

  <ul class="ticket-list">
    <% @tickets.each do |ticket| %>
      <a href="<%= ticket_path(ticket) %>">
        <li class="ticket">
          <label>ID:</label> <%= ticket.id %><br>
          <label>Request Number:</label> <%= ticket.request_number %><br>
          <label>Sequence Number:</label> <%= ticket.sequence_number %><br>
          <label>Request Type:</label> <%= ticket.request_type %><br>
          <label>Request Action:</label> <%= ticket.request_action %><br>
          <label>Response Due Date Time:</label> <%= ticket.response_due_date_time %><br>
          <label>Primary Service Area Code:</label> <%= ticket.primary_service_area_code %><br>
          <label>Excavator Company Name:</label> <%= ticket.excavator.company_name %><br>
          <label>Excavator Address:</label> <%= ticket.excavator.address %><br>
          <label>Excavator Crew Onsite:</label> <%= ticket.excavator.crew_onsite %><br>
        </li>
      </a>
    <% end %>
  </ul>

  <div class="pagination">
    <%= paginate @tickets %>
  </div>
</div>

app/views/tickets/show.html.erb
<h1>Ticket Details</h1>

 <div class="back-button">
  <%= link_to "Back", tickets_path, class: "back-link" %>
</div>

<div class="ticket-details">
  <div class="ticket-data">
    <label>ID: <%= @ticket.id %></label><br>
    <label>Request Number: <%= @ticket.request_number %></label><br>
    <label>Sequence Number: <%= @ticket.sequence_number %></label><br>
    <label>Request Type: <%= @ticket.request_type %></label><br>
    <label>Request Action: <%= @ticket.request_action %></label><br>
    <label>Response Due Date Time: <%= @ticket.response_due_date_time %></label><br>
    <label>Primary Service Area Code: <%= @ticket.primary_service_area_code %></label><br>
    <label>Excavator Company Name: <%= @ticket.excavator.company_name %></label><br>
    <label>Excavator Address: <%= @ticket.excavator.address %></label><br>
    <label>Excavator Crew Onsite: <%= @ticket.excavator.crew_onsite %></label><br>
  </div>

  <%= area_map [{geometry: {type: "Polygon", coordinates: [ @coordinates ] }}] %>
</div>